
services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak-sample-v1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_LOG_LEVEL=INFO
      - KC_LOG_CONSOLE_OUTPUT=json
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    command:
      - start-dev
      - "--features=preview"

  postgres:
    image: postgres:15
    container_name: postgres-keycloak
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: keycloak-auth-api
    ports:
      - 8082:80
    volumes:
      - ./api/app:/code/app

volumes:
  postgres_data:
